const $ = (s) => document.querySelector(s);
const icons = {
 grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
 chart:'<path d="M4 3v17h17M9 15v-4m5 4V7m5 8V4"/>',
 target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',
 link:'<path d="m10 13 4-4m-6 7-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m2 1 1-1a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0" transform="translate(1 1)"/>',
 refresh:'<path d="M20 7a9 9 0 1 0 1 8M20 3v5h-5"/>',
 download:'<path d="M12 3v12m-4-4 4 4 4-4M4 16v4h16v-4"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 check:'<path d="m6 12 4 4 8-9"/><rect x="3" y="3" width="18" height="18" rx="5"/>',
 flame:'<path d="M12 3c0 5-6 5-6 11a6 6 0 0 0 12 0c0-3-2-5-3-6 0 4-3 4-3 4 2-5 0-9 0-9Z"/>',
 book:'<path d="M12 6v15m0-15C8 3 4 3 2 4v14c4-1 7 0 10 3 3-3 6-4 10-3V4c-3-1-6-1-10 2Z"/>'
};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name] || icons.grid}</svg>`;
function decorate(){document.querySelectorAll('[data-icon]').forEach(el=>{if(!el.querySelector('svg'))el.insertAdjacentHTML('afterbegin',icon(el.dataset.icon));});}
const state={page:'overview',days:7,role:'parent',connected:false,subject:'전체',offset:0};
const TODAY=new Date(2026,8,13,12);
const dateKey = date => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const dayAt=n=>{const d=new Date(TODAY);d.setDate(d.getDate()+n);return d;};
const subjectInfo=[{name:'수학',class:'math',color:'#9875df',task:'이차방정식 문제 풀기'},{name:'영어',class:'english',color:'#b8a2ec',task:'영단어 복습 & 독해'},{name:'국어',class:'korean',color:'#d6c7f1',task:'문학 작품 정리하기'},{name:'과학',class:'science',color:'#eae2f7',task:'전기와 자기 개념 복습'}];
const minutes=[150,175,125,200,180,230,200];
const sessions=[];
for(let i=59;i>=0;i--){const total=i<7?minutes[6-i]:110+((i*37)%100);const date=dateKey(dayAt(-i));let remaining=total;[0,1,2,3].forEach((s,j)=>{const mins=j===3?remaining:Math.round(total*[.4,.28,.2][j]);remaining-=mins;sessions.push({id:`demo-${i}-${j}`,date,subject:subjectInfo[s].name,title:subjectInfo[s].task,minutes:mins,time:`${15+j}:00`});});}
const formatMins=m=>`${Math.floor(m/60)}시간 ${m%60}분`;
const shortDate=key=>`${Number(key.slice(5,7))}.${Number(key.slice(8,10))}`;
function selectedSessions(){const lower=dateKey(dayAt(-state.days+1));return sessions.filter(s=>s.date>=lower);}
function data(){const rows=selectedSessions(),total=rows.reduce((a,s)=>a+s.minutes,0),activeDays=new Set(rows.map(s=>s.date)).size;const previous=sessions.filter(s=>s.date<dateKey(dayAt(-state.days+1))&&s.date>=dateKey(dayAt(-state.days*2+1))).reduce((a,s)=>a+s.minutes,0);return {rows,total,activeDays,avg:Math.round(total/state.days),goal:state.days*180,change:previous?Math.round((total-previous)/previous*100):0};}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
function stat(label,value,unit,foot,name){return `<div class="stat"><div class="stat-top">${label}<span class="stat-icon">${icon(name)}</span></div><div class="stat-value">${value}<small>${unit}</small></div><div class="stat-foot">${foot}</div></div>`;}
function stats(){const d=data(),rate=Math.round(d.total/d.goal*100);return `<section class="stats" aria-label="학습 요약">${stat('총 공부 시간',Math.floor(d.total/60),'시간 '+d.total%60+'분',`<b>${d.change>=0?'↗':'↘'} ${Math.abs(d.change)}%</b> 이전 같은 기간 대비`,'clock')}${stat('하루 평균 공부',Math.floor(d.avg/60),'시간 '+d.avg%60+'분','하루의 집중이 차곡차곡 쌓였어요','chart')}${stat('학습 목표 달성률',rate,'%',`일일 목표 3시간 · ${state.days}일 기준`,'target')}${stat('꾸준히 공부한 날',d.activeDays,'일',`${state.days}일 중 공부 기록이 있는 날`,'flame')}</section>`;}
function chart(){const d=data();let groups=[];const count=state.days===7?7:6;for(let x=0;x<count;x++){const size=state.days===7?1:5;let current=0,previous=0;for(let j=0;j<size;j++){const offset=-state.days+1+x*size+j;current+=sessions.filter(s=>s.date===dateKey(dayAt(offset))).reduce((a,s)=>a+s.minutes,0);previous+=sessions.filter(s=>s.date===dateKey(dayAt(offset-state.days))).reduce((a,s)=>a+s.minutes,0);}const first=dayAt(-state.days+1+x*size);groups.push({current,previous,label:state.days===7?['일','월','화','수','목','금','토'][first.getDay()]:`${first.getMonth()+1}.${first.getDate()}`});}const max=Math.ceil(Math.max(...groups.flatMap(g=>[g.current,g.previous]))/60)*60;return `<section class="panel"><div class="panel-header"><h2>공부 시간의 흐름</h2><div class="legend"><span><i class="dot light"></i>이전 기간</span><span><i class="dot"></i>선택 기간</span></div></div><p class="panel-subtitle">${state.days===7?'매일 조금씩, 집중하는 시간이 늘고 있어요.':'5일 단위로 공부 시간을 모아봤어요.'}</p><div class="chart-wrap" role="img" aria-label="${groups.map(g=>`${g.label}: ${g.current}분, 이전 기간 ${g.previous}분`).join('; ')}"><div class="chart-grid">${[max,max*.75,max*.5,max*.25,0].map(v=>`<div><span>${(v/60).toFixed(v%60?1:0)}h</span></div>`).join('')}</div><div class="bars">${groups.map(g=>`<div class="bar-group"><div class="bar-pair"><div class="bar previous" style="height:${g.previous/max*100}%" data-label="이전 ${formatMins(g.previous)}"></div><div class="bar" style="height:${g.current/max*100}%" data-label="${formatMins(g.current)}"></div></div><span class="bar-label">${g.label}</span></div>`).join('')}</div></div><div class="chart-note">✧ &nbsp; ${state.days===7?'이번 주':'최근 30일'}, 하루 평균 <strong>${formatMins(d.avg)}</strong>을 공부했어요. 꾸준함을 칭찬해 주세요!</div></section>`;}
function subjects(){const d=data();let acc=0;const amounts=subjectInfo.map(s=>({...s,total:d.rows.filter(r=>r.subject===s.name).reduce((a,r)=>a+r.minutes,0)}));const gradient=amounts.map(s=>{const from=acc;acc+=s.total/d.total*100;return `${s.color} ${from}% ${acc}%`;}).join(',');return `<section class="panel"><div class="panel-header"><h2>과목별 집중 시간</h2>${icon('book')}</div><p class="panel-subtitle">관심과 노력이 모인 시간을 확인해요.</p><div class="donut-area"><div class="donut" style="background:conic-gradient(${gradient})" role="img" aria-label="${amounts.map(s=>`${s.name} ${s.total}분`).join(', ')}"><div class="donut-hole"><small>총 공부 시간</small><strong>${Math.floor(d.total/60)}<span style="font-size:13px;font-weight:400">시간</span> ${d.total%60}<span style="font-size:13px;font-weight:400">분</span></strong></div></div><div class="subjects">${amounts.map(s=>`<div class="subject"><i class="dot" style="background:${s.color}"></i>${s.name}<b>${Math.round(s.total/d.total*100)}%</b></div>`).join('')}</div></div><div class="subject-note"><span>가장 오래 집중한 과목</span><b>수학 · ${formatMins(amounts[0].total)}</b></div></section>`;}
function records(full=false){let rows=selectedSessions().sort((a,b)=>`${b.date}${b.time}`.localeCompare(`${a.date}${a.time}`));if(state.subject!=='전체'&&full)rows=rows.filter(r=>r.subject===state.subject);const count=rows.length;rows=full?rows.slice(state.offset,state.offset+12):rows.slice(0,4);return `<section class="panel ${full?'full-records':''}"><div class="panel-header"><h2>${full?'학습 기록 모아보기':'최근 학습 기록'}</h2>${full?`<select id="subjectFilter" aria-label="과목 필터"><option ${state.subject==='전체'?'selected':''}>전체</option>${subjectInfo.map(s=>`<option ${state.subject===s.name?'selected':''}>${s.name}</option>`).join('')}</select>`:'<button class="text-button" data-go="records">전체 보기 <span>↗</span></button>'}</div><p class="panel-subtitle">스스로 해낸 공부의 순간들이에요.</p><table class="record-table"><thead><tr><th scope="col">과목</th><th scope="col">학습 내용</th>${full?'<th scope="col">날짜</th>':''}<th scope="col">공부 시간</th><th scope="col">상태</th></tr></thead><tbody>${rows.map(r=>`<tr><td><span class="subject-badge ${subjectInfo.find(s=>s.name===r.subject).class}">${r.subject}</span></td><td>${r.title}</td>${full?`<td>${shortDate(r.date)} ${r.time}</td>`:''}<td>${r.minutes}분</td><td class="completion">✓ 완료</td></tr>`).join('')}</tbody></table>${full?`<div class="pagination"><span>${count}개 기록 · ${state.offset+1}–${Math.min(state.offset+12,count)}</span><div><button class="button" id="prevRecords" ${state.offset===0?'disabled':''}>이전</button><button class="button" id="nextRecords" ${state.offset+12>=count?'disabled':''}>다음</button></div></div>`:''}</section>`;}
function goal(){const d=data(),rate=Math.round(d.total/d.goal*100);return `<section class="panel goal-panel"><div class="panel-header"><h2>${state.days===7?'이번 주':'30일'}의 작은 목표</h2><span style="color:#c6b2e7">✧</span></div><div class="goal-row"><span>${state.days===7?'일주일':'30일'} ${d.goal/60}시간 공부하기</span><strong>${Math.min(rate,100)}%</strong></div><div class="progress" role="progressbar" aria-label="공부 시간 목표" aria-valuenow="${Math.min(rate,100)}" aria-valuemin="0" aria-valuemax="100"><span style="width:${Math.min(rate,100)}%"></span></div><div class="goal-caption">${formatMins(d.total)} / ${d.goal/60}시간</div><div class="reward"><div class="cat cat-trophy" role="img" aria-label="트로피를 안고 있는 스터디냥"></div><div><strong>${rate>=100?'이번 목표를 달성했어요!':'조금씩, 목표에 가까워지고 있어요'}</strong><p>${rate>=100?'꾸준히 노력한 지우에게<br>따뜻한 칭찬을 전해 주세요.':'오늘도 함께 응원해 주세요.<br>한 걸음씩이면 충분해요.'}</p></div></div></section>`;}
function connection(){return `<section class="panel connection-panel"><div class="cat cat-wave" role="img" aria-label="인사하는 스터디냥"></div><span class="eyebrow">BETTER, TOGETHER</span><h2>${state.connected?'지우의 스페이스와 연결했어요':'아이의 꾸준함을, 함께 응원해요'}</h2><p>학생이 초대 코드를 공유하면 학부모님도 공부 시간과 학습 기록, 목표 달성 현황을 확인할 수 있어요.</p><div class="connection-detail"><span>학생</span><strong>김지우 · 중학교 2학년</strong><span>공유 항목</span><strong>공부 시간, 과목별 기록, 목표</strong><span>연결 상태</span><strong>${state.connected?'연결 완료 체험':'연결 전'}</strong></div><div class="connection-actions"><button class="button primary" id="openConnect">${state.connected?'연결 과정 다시 보기':'초대 코드로 연결하기'}</button>${state.connected?'<button class="button" id="disconnect">체험 연결 해제</button>':''}</div><p class="mock-note">화면 체험용 목업이에요. 실제 계정이나 데이터는 연결되지 않아요.</p></section>`;}
function render(){const names={overview:'대시보드',records:'학습 기록',goals:'목표와 습관',connection:'가족 연결'};$('#crumb').textContent=names[state.page];$('#pageTitle').innerHTML=({overview:state.role==='parent'?'우리 아이의 성장이 보이는 곳':'나의 작은 집중이 쌓이는 곳',records:'차곡차곡 쌓인, 공부의 순간들',goals:'작은 약속이 만드는 큰 변화',connection:'함께 바라보는 아이의 성장'})[state.page]+'<span class="title-dot">.</span>';$('#pageSubtitle').textContent=state.page==='overview'?'꾸준히 쌓아온 작은 집중, 스터디냥과 함께 살펴보세요.':state.page==='records'?'과목별로 공부한 내용을 살펴보고, 꾸준한 노력을 발견해요.':state.page==='goals'?'어제보다 조금 더, 나만의 속도로 나아가요.':'아이의 공부 여정에 따뜻한 응원을 더해 주세요.';$('#profileName').textContent=state.role==='parent'?'학부모님':'김지우';$('.student-tag').textContent=state.role==='parent'?'나의 아이':'나의 기록';document.querySelectorAll('.avatar').forEach(a=>a.textContent=state.role==='parent'?'P':'지');$('#dateRange').textContent=`2026. ${shortDate(dateKey(dayAt(-state.days+1)))} — ${shortDate(dateKey(TODAY))}`;document.querySelectorAll('[data-days]').forEach(b=>{b.classList.toggle('selected',Number(b.dataset.days)===state.days);b.setAttribute('aria-pressed',Number(b.dataset.days)===state.days);});document.querySelectorAll('.nav').forEach(b=>{b.classList.toggle('active',b.dataset.page===state.page);if(b.dataset.page===state.page)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});$('.filterbar').hidden=state.page==='connection';$('#export').hidden=state.page==='connection';if(state.page==='overview')$('#view').innerHTML=`<section class="welcome"><span class="pill">지우와 스터디냥의 이번 주</span><h2>매일의 작은 집중이, <em>멋진 습관으로.</em></h2><p>지우는 이번 주 7일 동안 꾸준히 공부했어요.<br>결과보다 소중한 노력, 오늘도 함께 응원해 주세요.</p><span class="sparkle">✦</span><div class="cat cat-wave" role="img" aria-label="손을 흔들며 인사하는 스터디냥"></div></section>${stats()}<div class="grid-main">${chart()}${subjects()}</div><div class="grid-bottom">${records()}${goal()}</div>`;if(state.page==='records')$('#view').innerHTML=stats()+records(true);if(state.page==='goals')$('#view').innerHTML=`<div class="goals-grid">${goal()}<section class="panel"><div class="panel-header"><h2>매일 만나는 공부 습관</h2>${icon('check')}</div><p class="panel-subtitle">이번 주, 하루도 빠짐없이 공부했어요.</p><div class="habit-days">${['월','화','수','목','금','토','일'].map(x=>`<div class="habit-day done">${x}<span>✓</span></div>`).join('')}</div><div class="reward"><div class="cat cat-study" role="img" aria-label="책을 읽으며 공부하는 스터디냥"></div><div><strong>공부하는 나, 제법 멋져요.</strong><p>완벽한 하루보다 꾸준한 하루.<br>7일 연속의 노력을 응원해요!</p></div></div></section></div>`;if(state.page==='connection')$('#view').innerHTML=connection();decorate();}
function navigate(page){state.page=page;state.offset=0;render();}
document.addEventListener('click',event=>{const nav=event.target.closest('[data-page],[data-go]');if(nav)navigate(nav.dataset.page||nav.dataset.go);const days=event.target.closest('[data-days]');if(days){state.days=Number(days.dataset.days);state.offset=0;render();}if(event.target.closest('#openConnect')){$('#connectionError').textContent='';$('#accessKey').value='';$('#connectDialog').showModal();}if(event.target.closest('.dialog-close'))$('#connectDialog').close();if(event.target.closest('#disconnect')){state.connected=false;render();toast('체험 연결을 해제했어요.');}if(event.target.closest('#prevRecords')){state.offset=Math.max(0,state.offset-12);render();}if(event.target.closest('#nextRecords')){state.offset+=12;render();}});
document.addEventListener('change',event=>{if(event.target.id==='subjectFilter'){state.subject=event.target.value;state.offset=0;render();}});
$('#role').addEventListener('change',e=>{state.role=e.target.value;render();toast(`${state.role==='parent'?'학부모':'학생'} 화면으로 전환했어요.`);});
$('#refresh').addEventListener('click',()=>{render();$('#syncText').textContent='방금 새로고침 · 예시 데이터';toast('예시 기록을 새로 불러왔어요.');});
$('#export').addEventListener('click',()=>{let rows=selectedSessions();if(state.page==='records'&&state.subject!=='전체')rows=rows.filter(r=>r.subject===state.subject);const csv='\uFEFF'+[['구분','날짜','과목','학습 내용','공부 시간(분)'],...rows.map(r=>['예시 데이터',r.date,r.subject,r.title,r.minutes])].map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`스터디냥_예시학습기록_${state.days}일.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('예시 학습 기록을 CSV로 저장했어요.');});
$('#connectForm').addEventListener('submit',event=>{event.preventDefault();if($('#accessKey').value.trim().toUpperCase()!=='NYANG26'){$('#connectionError').textContent='체험 코드는 NYANG26이에요. 다시 입력해 주세요.';return;}state.connected=true;$('#connectDialog').close();render();toast('지우의 스페이스 연결을 체험했어요.');});
$('#connectDialog').addEventListener('click',e=>{if(e.target===$('#connectDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
render();

const entryPage = new URLSearchParams(location.search).get("page");
if (["overview", "records", "goals", "connection"].includes(entryPage)) navigate(entryPage);
