const $=s=>document.querySelector(s);
const state={action:'idle',until:0,targetX:0,targetY:0,yaw:0,voice:false,stream:null,detector:null,cameraBusy:false,generation:0,lastDetection:0,lastFrame:-1,faceSeen:false};
let frameId;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function say(text,action='idle'){$('#speech').textContent=text;state.action=action;state.until=performance.now()+4300;$('#mood').textContent=({pet:'골골… 기분이 좋아요',wave:'반갑다고 인사해요',cheer:'힘껏 응원하고 있어요',rest:'잠깐, 같이 쉬어가요',talk:'이야기를 나누고 있어요',idle:'함께할 준비가 됐어요'})[action];if(state.voice&&'speechSynthesis' in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ko-KR';u.rate=.95;u.pitch=1.3;u.onend=()=>{if(state.action==='talk')state.until=0;};speechSynthesis.speak(u);}}
const actionLines={pet:'골골… 따뜻한 손길, 정말 좋아. 고마워 ♡',wave:'안녕! 여기서 너를 기다리고 있었어. 만나서 반가워!',cheer:'지금도 충분히 잘하고 있어! 작은 한 걸음도 멋진 시작이야.',rest:'어깨를 살짝 내리고, 천천히 숨을 쉬어봐. 나도 같이 쉴게.'};
document.querySelectorAll('.actions [data-action]').forEach(b=>b.addEventListener('click',()=>say(actionLines[b.dataset.action],b.dataset.action)));
$('#voice').addEventListener('click',()=>{if(!('speechSynthesis' in window)){$('#voice').textContent='음성을 지원하지 않아요';return;}state.voice=!state.voice;$('#voice').setAttribute('aria-pressed',state.voice);$('#voice').textContent=state.voice?'음성 읽기 켜짐':'음성 읽기 꺼짐';if(!state.voice)speechSynthesis.cancel();});
function addMessage(text,user=false){const div=document.createElement('div');div.className=`message ${user?'user-message':'cat-message'}`;const label=document.createElement('span');label.textContent=user?'나':'냥냥이';const p=document.createElement('p');p.textContent=text;div.append(label,p);$('#messages').append(div);while($('#messages').children.length>40)$('#messages').firstElementChild.remove();$('#messages').scrollTop=$('#messages').scrollHeight;}
function reply(text){if(/힘들|어려|못하|지치|스트레스/.test(text))return ['어려운 날도 있지. 오늘 어려웠던 것 하나만 골라볼까? 작은 부분부터 같이 시작해 보자.','pet'];if(/응원|화이팅|잘할/.test(text))return [actionLines.cheer,'cheer'];if(/쉬|졸|피곤/.test(text))return [actionLines.rest,'rest'];if(/안녕|반가/.test(text))return [actionLines.wave,'wave'];if(/수학|영어|과학|공부/.test(text))return ['오늘은 딱 25분, 한 가지에만 집중해 볼까? 끝나면 잠깐 쉬면서 나에게 알려줘!','talk'];if(/고마|좋아|귀여/.test(text))return ['그 말 들으니까 꼬리가 절로 움직여! 나도 너와 함께 있는 시간이 좋아 ♡','pet'];return ['네 이야기를 듣고 있어. 지금 가장 하고 싶은 일은 뭐야? 이 화면에서는 준비된 답변으로 이야기해 볼 수 있어.','talk'];}
let chatTimer;
function send(text){text=text.trim().slice(0,300);if(!text)return;clearTimeout(chatTimer);addMessage(text,true);$('#chatInput').value='';const [answer,action]=reply(text);chatTimer=setTimeout(()=>{addMessage(answer);say(answer,action);},500);}
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();send($('#chatInput').value);});document.querySelectorAll('.suggestions button').forEach(b=>b.addEventListener('click',()=>send(b.textContent)));
$('#reset').addEventListener('click',()=>{state.yaw=0;state.targetX=0;state.targetY=0;say('다시 눈을 맞춰볼까?');});
const character=$('#character');
$('#stage').addEventListener('pointermove',e=>{const r=$('#stage').getBoundingClientRect();if(!state.faceSeen){state.targetX=clamp(((e.clientX-r.left)/r.width-.5)*2,-1,1);state.targetY=clamp(((e.clientY-r.top)/r.height-.5)*2,-1,1);}});
$('#stage').addEventListener('pointerleave',()=>{if(!state.faceSeen){state.targetX=0;state.targetY=0;}});
character.addEventListener('click',()=>say(actionLines.pet,'pet'));
let lastAction='';
function animate2D(now){
 const active=now<state.until?state.action:'idle';
 if(lastAction!==active){lastAction=active;character.dataset.action=active;character.dataset.pose=({rest:'study',talk:'study',cheer:'trophy'})[active]||'wave';
 character.setAttribute('aria-label',({study:'책을 읽는 냥냥이, 눌러서 쓰다듬기',trophy:'트로피를 안은 냥냥이, 눌러서 쓰다듬기',wave:'손을 흔드는 냥냥이, 눌러서 쓰다듬기'})[character.dataset.pose]);
 document.querySelectorAll('[data-action]').forEach(b=>{if(b!==character){b.classList.toggle('active',b.dataset.action===active);b.setAttribute('aria-pressed',b.dataset.action===active);}});
 $('#reaction').textContent=({pet:'♡',wave:'안녕!',cheer:'잘하고 있어!',rest:'쉬어가도 괜찮아',talk:'이야기 듣는 중'})[active]||'';
 if(active==='idle')$('#mood').textContent='함께할 준비가 됐어요';
 }
 character.style.setProperty('--follow-x',`${reduced?0:state.targetX*10}px`);
 character.style.setProperty('--follow-y',`${reduced?0:state.targetY*5}px`);
 character.style.setProperty('--tilt',`${reduced?0:state.targetX*2}deg`);
 frameId=requestAnimationFrame(animate2D);
}
function stopCamera(message='카메라가 꺼졌어요. 포인터로도 교감할 수 있어요.'){state.generation++;if(state.stream)state.stream.getTracks().forEach(t=>t.stop());state.stream=null;state.faceSeen=false;state.cameraBusy=false;$('#video').srcObject=null;$('#video').hidden=true;$('#cameraEmpty').hidden=false;$('#faceBox').hidden=true;$('#cameraBadge').textContent='카메라 꺼짐';$('#cameraButton').textContent='카메라 켜고 눈 맞추기';$('#cameraButton').disabled=false;$('#cameraInfo').textContent=message;$('#trackingMode').textContent='움직임에 반응하고 있어요';state.targetX=0;state.targetY=0;}
async function startCamera(){if(state.stream||state.cameraBusy){stopCamera();return;}if(!navigator.mediaDevices?.getUserMedia){$('#cameraInfo').textContent='이 브라우저에서는 카메라를 사용할 수 없어요. HTTPS 주소로 Chrome 또는 Safari에서 열어 주세요.';return;}state.cameraBusy=true;const generation=++state.generation;$('#cameraButton').textContent='카메라 준비 취소';$('#cameraInfo').textContent='얼굴 인식 기능을 준비하고 있어요. 처음에는 잠시 걸릴 수 있어요.';try{if(!state.detector){const {FaceDetector,FilesetResolver}=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/vision_bundle.mjs');const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm');const detector=await FaceDetector.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/1/blaze_face_short_range.tflite'},runningMode:'VIDEO',minDetectionConfidence:.6});if(generation!==state.generation){detector.close();return;}state.detector=detector;}if(generation!==state.generation)return;$('#cameraInfo').textContent='브라우저의 카메라 허용을 선택해 주세요.';const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});if(generation!==state.generation){stream.getTracks().forEach(t=>t.stop());return;}state.stream=stream;$('#video').srcObject=stream;await $('#video').play();if(generation!==state.generation)return;$('#video').hidden=false;$('#cameraEmpty').hidden=true;$('#cameraButton').textContent='카메라 끄기';$('#cameraBadge').textContent='얼굴 찾는 중';$('#cameraInfo').textContent='영상은 기기 안에서만 처리돼요. 화면 앞에서 천천히 좌우로 움직여 보세요.';state.cameraBusy=false;state.lastFrame=-1;state.lastDetection=0;stream.getVideoTracks()[0].onended=()=>stopCamera();requestAnimationFrame(trackFace);}catch(error){if(generation!==state.generation)return;stopCamera(error.name==='NotAllowedError'?'카메라 권한이 허용되지 않았어요. 브라우저 설정에서 허용한 뒤 다시 눌러 주세요.':error.name==='NotFoundError'?'사용할 수 있는 카메라를 찾지 못했어요. 카메라를 연결한 뒤 다시 시도해 주세요.':'카메라 또는 인식 기능을 불러오지 못했어요. 연결을 확인한 뒤 다시 시도해 주세요.');}}
function trackFace(now){if(!state.stream)return;const video=$('#video');if(now-state.lastDetection>140&&video.readyState>=2&&video.currentTime!==state.lastFrame){state.lastDetection=now;state.lastFrame=video.currentTime;try{const faces=state.detector.detectForVideo(video,now).detections;const b=faces[0]?.boundingBox;state.faceSeen=!!b;if(b){const x=(b.originX+b.width/2)/video.videoWidth,y=(b.originY+b.height/2)/video.videoHeight;state.targetX=clamp((.5-x)*2,-1,1);state.targetY=clamp((y-.5)*2,-1,1);$('#cameraBadge').textContent='눈 맞추는 중';$('#trackingMode').textContent='얼굴 위치에 반응하고 있어요';const box=$('#faceBox');box.hidden=false;box.style.left=`${(1-(b.originX+b.width)/video.videoWidth)*100}%`;box.style.top=`${b.originY/video.videoHeight*100}%`;box.style.width=`${b.width/video.videoWidth*100}%`;box.style.height=`${b.height/video.videoHeight*100}%`;}else{$('#faceBox').hidden=true;$('#cameraBadge').textContent='얼굴 찾는 중';$('#trackingMode').textContent='화면 앞에 얼굴을 보여 주세요';state.targetX=0;state.targetY=0;}}catch{stopCamera('얼굴 인식이 멈췄어요. 카메라를 다시 켜 주세요.');return;}}requestAnimationFrame(trackFace);}
$('#cameraButton').addEventListener('click',startCamera);
window.addEventListener('pagehide',()=>{stopCamera();state.detector?.close();state.detector=null;if('speechSynthesis' in window)speechSynthesis.cancel();clearTimeout(chatTimer);cancelAnimationFrame(frameId);});document.addEventListener('visibilitychange',()=>{if(document.hidden){stopCamera('다른 화면으로 이동해 카메라를 껐어요. 다시 켜서 교감할 수 있어요.');if('speechSynthesis' in window)speechSynthesis.cancel();}});
window.addEventListener('pageshow',()=>{cancelAnimationFrame(frameId);frameId=requestAnimationFrame(animate2D);});
frameId=requestAnimationFrame(animate2D);
