const $=s=>document.querySelector(s);
const state={action:'idle',until:0,targetX:0,targetY:0,yaw:0,voice:false,stream:null,detector:null,cameraBusy:false,generation:0,lastDetection:0,lastFrame:-1,faceSeen:false};
let rig,renderer,scene,camera,THREE;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function say(text,action='idle'){$('#speech').textContent=text;state.action=action;state.until=performance.now()+4300;$('#mood').textContent=({pet:'골골… 기분이 좋아요',wave:'반갑다고 인사해요',cheer:'힘껏 응원하고 있어요',rest:'잠깐, 같이 쉬어가요',talk:'이야기를 나누고 있어요',idle:'함께할 준비가 됐어요'})[action];if(state.voice&&'speechSynthesis' in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ko-KR';u.rate=.95;u.pitch=1.3;u.onend=()=>{if(state.action==='talk')state.until=0;};speechSynthesis.speak(u);}}
const actionLines={pet:'골골… 따뜻한 손길, 정말 좋아. 고마워 ♡',wave:'안녕! 여기서 너를 기다리고 있었어. 만나서 반가워!',cheer:'지금도 충분히 잘하고 있어! 작은 한 걸음도 멋진 시작이야.',rest:'어깨를 살짝 내리고, 천천히 숨을 쉬어봐. 나도 같이 쉴게.'};
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>say(actionLines[b.dataset.action],b.dataset.action)));
$('#voice').addEventListener('click',()=>{if(!('speechSynthesis' in window)){$('#voice').textContent='음성을 지원하지 않아요';return;}state.voice=!state.voice;$('#voice').setAttribute('aria-pressed',state.voice);$('#voice').textContent=state.voice?'음성 읽기 켜짐':'음성 읽기 꺼짐';if(!state.voice)speechSynthesis.cancel();});
function addMessage(text,user=false){const div=document.createElement('div');div.className=`message ${user?'user-message':'cat-message'}`;const label=document.createElement('span');label.textContent=user?'나':'냥냥이';const p=document.createElement('p');p.textContent=text;div.append(label,p);$('#messages').append(div);while($('#messages').children.length>40)$('#messages').firstElementChild.remove();$('#messages').scrollTop=$('#messages').scrollHeight;}
function reply(text){if(/힘들|어려|못하|지치|스트레스/.test(text))return ['어려운 날도 있지. 오늘 어려웠던 것 하나만 골라볼까? 작은 부분부터 같이 시작해 보자.','pet'];if(/응원|화이팅|잘할/.test(text))return [actionLines.cheer,'cheer'];if(/쉬|졸|피곤/.test(text))return [actionLines.rest,'rest'];if(/안녕|반가/.test(text))return [actionLines.wave,'wave'];if(/수학|영어|과학|공부/.test(text))return ['오늘은 딱 25분, 한 가지에만 집중해 볼까? 끝나면 잠깐 쉬면서 나에게 알려줘!','talk'];if(/고마|좋아|귀여/.test(text))return ['그 말 들으니까 꼬리가 절로 움직여! 나도 너와 함께 있는 시간이 좋아 ♡','pet'];return ['네 이야기를 듣고 있어. 지금 가장 하고 싶은 일은 뭐야? 이 화면에서는 준비된 답변으로 이야기해 볼 수 있어.','talk'];}
let chatTimer;
function send(text){text=text.trim().slice(0,300);if(!text)return;clearTimeout(chatTimer);addMessage(text,true);$('#chatInput').value='';const [answer,action]=reply(text);chatTimer=setTimeout(()=>{addMessage(answer);say(answer,action);},500);}
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();send($('#chatInput').value);});document.querySelectorAll('.suggestions button').forEach(b=>b.addEventListener('click',()=>send(b.textContent)));
$('#reset').addEventListener('click',()=>{state.yaw=0;state.targetX=0;state.targetY=0;say('다시 눈을 맞춰볼까?');});
let drag=null;
$('#stage').addEventListener('pointerdown',e=>{drag={x:e.clientX,yaw:state.yaw,moved:false};$('#stage').setPointerCapture(e.pointerId);});
$('#stage').addEventListener('pointermove',e=>{const r=$('#stage').getBoundingClientRect();if(!state.faceSeen){state.targetX=((e.clientX-r.left)/r.width-.5)*2;state.targetY=((e.clientY-r.top)/r.height-.5)*2;}if(drag){if(Math.abs(e.clientX-drag.x)>6)drag.moved=true;state.yaw=clamp(drag.yaw+(e.clientX-drag.x)*.008,-1.3,1.3);}});
$('#stage').addEventListener('pointerup',()=>{if(drag&&!drag.moved)say(actionLines.pet,'pet');drag=null;});$('#stage').addEventListener('pointercancel',()=>{drag=null;});$('#stage').addEventListener('pointerleave',()=>{if(!state.faceSeen){state.targetX=0;state.targetY=0;}});
function sphere(parent,mat,x,y,z,sx,sy,sz){const mesh=new THREE.Mesh(new THREE.SphereGeometry(1,40,28),mat);mesh.position.set(x,y,z);mesh.scale.set(sx,sy,sz);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
function line(parent,points,mat,r=.014){const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p)));const m=new THREE.Mesh(new THREE.TubeGeometry(curve,32,r,8,false),mat);parent.add(m);return m;}
function buildCat(){const root=new THREE.Group();scene.add(root);const material=(color,roughness=.8)=>new THREE.MeshStandardMaterial({color,roughness});const black=material('#35323e'),white=material('#fffaf6'),pink=material('#ecaaa9'),purple=material('#8960d6'),dark=material('#1b1720'),eyeMat=material('#110f15',.09),shine=material('#ffffff',.1);
 const body=new THREE.Group();root.add(body);sphere(body,black,0,1.13,0,.72,.94,.55);sphere(body,white,0,1.05,.44,.44,.65,.19);sphere(body,black,-.54,.49,.06,.37,.45,.4);sphere(body,black,.54,.49,.06,.37,.45,.4);sphere(body,white,-.43,.25,.46,.30,.25,.37);sphere(body,white,.43,.25,.46,.30,.25,.37);
 const tail=new THREE.Group();tail.position.set(-.52,.35,-.25);root.add(tail);line(tail,[[0,0,0],[-.6,.03,0],[-.95,.38,.05],[-1.05,.85,.08]],black,.17);sphere(tail,white,-1.05,.89,.08,.17,.24,.17);
 const arms=[];for(const sign of [-1,1]){const arm=new THREE.Group();arm.position.set(sign*.54,1.48,.13);body.add(arm);sphere(arm,black,sign*.10,-.37,.13,.23,.47,.25);sphere(arm,white,sign*.12,-.70,.24,.235,.25,.27);arms.push(arm);}
 const collar=new THREE.Mesh(new THREE.TorusGeometry(.47,.068,16,64),purple);collar.rotation.x=Math.PI/2;collar.position.set(0,1.84,0);body.add(collar);sphere(body,white,0,1.62,.55,.15,.16,.05);sphere(body,white,-.10,1.76,.55,.055,.085,.05);sphere(body,white,.10,1.76,.55,.055,.085,.05);sphere(body,dark,-.047,1.65,.60,.013,.02,.01);sphere(body,dark,.047,1.65,.60,.013,.02,.01);
 const head=new THREE.Group();head.position.set(0,2.28,.025);root.add(head);sphere(head,black,0,0,0,1,.84,.72);
 function ear(sign){const group=new THREE.Group();group.position.set(sign*.69,.53,0);group.rotation.z=-sign*.24;const shape=new THREE.Shape();shape.moveTo(-.30,0);shape.quadraticCurveTo(-.23,.48,0,.78);shape.quadraticCurveTo(.25,.49,.31,0);shape.closePath();const geo=new THREE.ExtrudeGeometry(shape,{depth:.20,bevelEnabled:true,bevelThickness:.10,bevelSize:.07,bevelSegments:5,steps:1});const mesh=new THREE.Mesh(geo,black);mesh.position.z=-.2;mesh.castShadow=true;group.add(mesh);const inset=new THREE.Mesh(new THREE.ShapeGeometry(shape),pink);inset.scale.set(.65,.70,1);inset.position.set(0,.055,.115);group.add(inset);head.add(group);return group;}
 const ears=[ear(-1),ear(1)];sphere(head,white,0,-.32,.51,.60,.40,.27);sphere(head,white,0,-.06,.67,.18,.39,.065);sphere(head,white,-.21,-.34,.74,.27,.21,.11);sphere(head,white,.21,-.34,.74,.27,.21,.11);
 const eyes=[];for(const sign of [-1,1]){const eye=new THREE.Group();eye.position.set(sign*.43,.04,.64);head.add(eye);sphere(eye,eyeMat,0,0,0,.205,.255,.14);sphere(eye,shine,-.053,.075,.12,.055,.059,.017);sphere(eye,shine,.046,-.065,.13,.021,.024,.01);eyes.push(eye);sphere(head,pink,sign*.66,-.27,.62,.13,.065,.027);}
 const nose=sphere(head,pink,0,-.26,.88,.09,.065,.058);nose.rotation.z=Math.PI;
 const mouth=new THREE.Group();head.add(mouth);line(mouth,[[0,-.30,.89],[0,-.39,.88],[-.10,-.43,.84],[-.16,-.38,.82]],dark,.012);line(mouth,[[0,-.39,.88],[.10,-.43,.84],[.16,-.38,.82]],dark,.012);
 const whisker=material('#b9b2bd');for(const sign of [-1,1])for(let i=0;i<3;i++)line(head,[[sign*.63,-.34+i*.08,.59],[sign*.93,-.32+i*.12,.47],[sign*1.15,-.37+i*.17,.36]],whisker,.008);
 return {root,body,head,tail,arms,eyes,ears,mouth};
}
async function init3D(){try{THREE=await import('./vendor/three.module.js');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(0,2.5,8.3);camera.lookAt(0,1.7,0);renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;$('#stage').append(renderer.domElement);scene.add(new THREE.HemisphereLight('#ffffff','#afa0c4',2.3));const key=new THREE.DirectionalLight('#fff5ee',3.2);key.position.set(-3,6,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.normalBias=.03;scene.add(key);const rim=new THREE.DirectionalLight('#d7c7ff',2);rim.position.set(3,4,-3);scene.add(rim);const ground=new THREE.Mesh(new THREE.CircleGeometry(3.3,80),new THREE.ShadowMaterial({opacity:.12}));ground.rotation.x=-Math.PI/2;ground.position.y=.01;ground.receiveShadow=true;scene.add(ground);rig=buildCat();const resize=()=>{const r=$('#stage').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();};new ResizeObserver(resize).observe($('#stage'));resize();$('#loading').hidden=true;renderer.setAnimationLoop(animate);}catch(error){$('#loading').textContent='3D 화면을 열지 못했어요. WebGL을 지원하는 최신 브라우저에서 다시 열어 주세요. 대화와 카메라는 계속 사용할 수 있어요.';console.error('3D initialization failed',error);}}
function animate(now){if(document.hidden)return;const t=now/1000,active=now<state.until?state.action:'idle';const moving=reduced?0:1;rig.root.rotation.y+=(state.yaw-rig.root.rotation.y)*.07;rig.body.scale.y=1+Math.sin(t*2)*.012*moving;rig.head.position.y=2.28+Math.sin(t*2)*.018*moving;const tilt=active==='pet'?Math.sin(t*3)*.12:active==='rest'?.11:0;rig.head.rotation.y+=(state.targetX*.32-rig.head.rotation.y)*.065;rig.head.rotation.x+=(state.targetY*.20-rig.head.rotation.x)*.065;rig.head.rotation.z+=(tilt-rig.head.rotation.z)*.06;rig.tail.rotation.y=Math.sin(t*(active==='pet'?5:1.8))*.18*moving;rig.ears.forEach((ear,i)=>ear.rotation.z=(i===0?.24:-.24)+Math.sin(t*1.3+i)*.025*moving);const blink=active==='pet'||active==='rest'?.12:(Math.sin(t*1.35)> .992?.1:1);rig.eyes.forEach(e=>e.scale.y+=(blink-e.scale.y)*.5);rig.arms[0].rotation.z+=( (active==='wave'? -2.05+Math.sin(t*9)*.25:active==='cheer'?-2.3:0)-rig.arms[0].rotation.z)*.12;rig.arms[1].rotation.z+=((active==='cheer'?2.3:0)-rig.arms[1].rotation.z)*.12;rig.root.position.y=active==='cheer'?Math.abs(Math.sin(t*5))*.1*moving:0;rig.mouth.scale.y=active==='talk'?1+Math.sin(t*15)*.18:1;renderer.render(scene,camera);}
function stopCamera(message='카메라가 꺼졌어요. 포인터로도 교감할 수 있어요.'){state.generation++;if(state.stream)state.stream.getTracks().forEach(t=>t.stop());state.stream=null;state.faceSeen=false;state.cameraBusy=false;$('#video').srcObject=null;$('#video').hidden=true;$('#cameraEmpty').hidden=false;$('#faceBox').hidden=true;$('#cameraBadge').textContent='카메라 꺼짐';$('#cameraButton').textContent='카메라 켜고 눈 맞추기';$('#cameraButton').disabled=false;$('#cameraInfo').textContent=message;$('#trackingMode').textContent='포인터를 따라 보고 있어요';state.targetX=0;state.targetY=0;}
async function startCamera(){if(state.stream||state.cameraBusy){stopCamera();return;}if(!navigator.mediaDevices?.getUserMedia){$('#cameraInfo').textContent='이 브라우저에서는 카메라를 사용할 수 없어요. HTTPS 주소로 Chrome 또는 Safari에서 열어 주세요.';return;}state.cameraBusy=true;const generation=++state.generation;$('#cameraButton').textContent='카메라 준비 취소';$('#cameraInfo').textContent='얼굴 인식 기능을 준비하고 있어요. 처음에는 잠시 걸릴 수 있어요.';try{if(!state.detector){const {FaceDetector,FilesetResolver}=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/vision_bundle.mjs');const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm');const detector=await FaceDetector.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/1/blaze_face_short_range.tflite'},runningMode:'VIDEO',minDetectionConfidence:.6});if(generation!==state.generation){detector.close();return;}state.detector=detector;}if(generation!==state.generation)return;$('#cameraInfo').textContent='브라우저의 카메라 허용을 선택해 주세요.';const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});if(generation!==state.generation){stream.getTracks().forEach(t=>t.stop());return;}state.stream=stream;$('#video').srcObject=stream;await $('#video').play();if(generation!==state.generation)return;$('#video').hidden=false;$('#cameraEmpty').hidden=true;$('#cameraButton').textContent='카메라 끄기';$('#cameraBadge').textContent='얼굴 찾는 중';$('#cameraInfo').textContent='영상은 기기 안에서만 처리돼요. 화면 앞에서 천천히 좌우로 움직여 보세요.';state.cameraBusy=false;state.lastFrame=-1;state.lastDetection=0;stream.getVideoTracks()[0].onended=()=>stopCamera();requestAnimationFrame(trackFace);}catch(error){if(generation!==state.generation)return;stopCamera(error.name==='NotAllowedError'?'카메라 권한이 허용되지 않았어요. 브라우저 설정에서 허용한 뒤 다시 눌러 주세요.':error.name==='NotFoundError'?'사용할 수 있는 카메라를 찾지 못했어요. 카메라를 연결한 뒤 다시 시도해 주세요.':'카메라 또는 인식 기능을 불러오지 못했어요. 연결을 확인한 뒤 다시 시도해 주세요.');}}
function trackFace(now){if(!state.stream)return;const video=$('#video');if(now-state.lastDetection>140&&video.readyState>=2&&video.currentTime!==state.lastFrame){state.lastDetection=now;state.lastFrame=video.currentTime;try{const faces=state.detector.detectForVideo(video,now).detections;const b=faces[0]?.boundingBox;state.faceSeen=!!b;if(b){const x=(b.originX+b.width/2)/video.videoWidth,y=(b.originY+b.height/2)/video.videoHeight;state.targetX=clamp((.5-x)*2,-1,1);state.targetY=clamp((y-.5)*2,-1,1);$('#cameraBadge').textContent='눈 맞추는 중';$('#trackingMode').textContent='얼굴을 따라 보고 있어요';const box=$('#faceBox');box.hidden=false;box.style.left=`${(1-(b.originX+b.width)/video.videoWidth)*100}%`;box.style.top=`${b.originY/video.videoHeight*100}%`;box.style.width=`${b.width/video.videoWidth*100}%`;box.style.height=`${b.height/video.videoHeight*100}%`;}else{$('#faceBox').hidden=true;$('#cameraBadge').textContent='얼굴 찾는 중';$('#trackingMode').textContent='화면 앞에 얼굴을 보여 주세요';state.targetX=0;state.targetY=0;}}catch{stopCamera('얼굴 인식이 멈췄어요. 카메라를 다시 켜 주세요.');return;}}requestAnimationFrame(trackFace);}
$('#cameraButton').addEventListener('click',startCamera);
window.addEventListener('pagehide',()=>{stopCamera();state.detector?.close();state.detector=null;if('speechSynthesis' in window)speechSynthesis.cancel();clearTimeout(chatTimer);renderer?.setAnimationLoop(null);});document.addEventListener('visibilitychange',()=>{if(document.hidden){stopCamera('다른 화면으로 이동해 카메라를 껐어요. 다시 켜서 교감할 수 있어요.');if('speechSynthesis' in window)speechSynthesis.cancel();}});
init3D();
